version: '3'

services:
  reverse-proxy:
    image: traefik:2.0 # The official v2.0 Traefik docker image
    container_name: traefik
    command: --api --providers.docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "443:443"   # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json

  whoami:
    image: containous/whoami # A container that exposes an API to show its IP address
    labels:
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.strip_whoami.stripprefix.prefixes=/whoami"
      - "traefik.http.routers.whoami.rule=Host(`wf.tmshv.com`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.middlewares=https_redirect"
      - "traefik.http.routers.whoami-tls.rule=Host(`wf.tmshv.com`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami-tls.middlewares=strip_whoami"
      - "traefik.http.routers.whoami-tls.tls"

  wf-app:
    image: tmshv/waterfront-app
    labels:
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wf-app.rule=Host(`wf.tmshv.com`)"
      - "traefik.http.routers.wf-app.middlewares=https_redirect"
      - "traefik.http.routers.wf-app-tls.rule=Host(`wf.tmshv.com`)"
      - "traefik.http.routers.wf-app-tls.tls"

  wf-data:
    image: tmshv/wf-data
    labels:
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.wf-data-strip.stripprefix.prefixes=/data"
      - "traefik.http.routers.wf-data.rule=Host(`wf.tmshv.com`) && PathPrefix(`/data`)"
      - "traefik.http.routers.wf-data.middlewares=https_redirect"
      - "traefik.http.routers.wf-data-tls.rule=Host(`wf.tmshv.com`) && PathPrefix(`/data`)"
      - "traefik.http.routers.wf-data-tls.middlewares=wf-data-strip"
      - "traefik.http.routers.wf-data-tls.priority=100"
      - "traefik.http.routers.wf-data-tls.tls"

  wf-database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "wf"
      MYSQL_ROOT_PASSWORD: "ZjcZO3LcQUqevJ2Kt80Ad"
      MYSQL_USER: "master"
      MYSQL_PASSWORD: "p07GDeRiQFvkG7mYRylu8"
    ports:
      - 3306:3306
    volumes:
      - ./wf_mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  directus-api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: wf-database
      DATABASE_NAME: "wf"
      DATABASE_USERNAME: "master"
      DATABASE_PASSWORD: "p07GDeRiQFvkG7mYRylu8"
      ADMIN_EMAIL: "roman@tmshv.ru"
      ADMIN_PASSWORD: "gB1~lvp9kdid6tWN~OO28"
      #STORAGE_ADAPTER: "local"
      #STORAGE_ROOT: "public/uploads/_/originals"
      STORAGE_ROOT_URL: "/api/uploads/_/originals"
      #STORAGE_THUMB_URL: "public/uploads/_/thumbnails"
      #STORAGE_KEY: "s3-key"
      #STORAGE_SECRET: "s3-secret"
      #STORAGE_REGION: "us-east-1"
      #STORAGE_VERSION: "latest"
      #STORAGE_BUCKET: "directus"
    volumes:
      - ./directus_api-php.ini:/etc/php7/php.ini
      - ./directus_api-file.php:/var/www/html/src/helpers/file.php
      - ./wf_data/uploads:/var/www/html/public/uploads
      - ./wf_data/thumbnails:/var/www/html/public/thumbnails
    ports:
      - 3300:80
    labels:
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.directus_api_fixpath.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.thumbnail_redirect.redirectregex.regex=^https?://wf.tmshv.com/(.*)"
      - "traefik.http.middlewares.thumbnail_redirect.redirectregex.replacement=https://wf.tmshv.com/api/$$1"
      - "traefik.http.routers.directus-api.rule=Host(`wf.tmshv.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.directus-api.middlewares=https_redirect"
      - "traefik.http.routers.directus-api-tls.rule=Host(`wf.tmshv.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.directus-api-tls.middlewares=directus_api_fixpath"
      - "traefik.http.routers.directus-api-tls.tls"
      - "traefik.http.routers.directus-thumbnails.rule=Host(`wf.tmshv.com`) && PathPrefix(`/thumbnail`)"
      - "traefik.http.routers.directus-thumbnails.middlewares=https_redirect"
      - "traefik.http.routers.directus-thumbnails-tls.rule=Host(`wf.tmshv.com`) && PathPrefix(`/thumbnail`)"
      - "traefik.http.routers.directus-thumbnails-tls.middlewares=thumbnail_redirect"
      - "traefik.http.routers.directus-thumbnails-tls.priority=100"
      - "traefik.http.routers.directus-thumbnails-tls.tls"

  directus-app:
    image: directus/app:latest
    environment:
      ROUTER_BASE_URL: "/edit"
      API_ENDPOINT: "API; https://wf.tmshv.com/api/_/"
    labels:
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.directus_app_fixpath.stripprefix.prefixes=/edit"
      - "traefik.http.routers.directus-app.rule=Host(`wf.tmshv.com`) && PathPrefix(`/edit`)"
      - "traefik.http.routers.directus-app.middlewares=https_redirect"
      - "traefik.http.routers.directus-app-tls.rule=Host(`wf.tmshv.com`) && PathPrefix(`/edit`)"
      - "traefik.http.routers.directus-app-tls.middlewares=directus_app_fixpath"
      - "traefik.http.routers.directus-app-tls.tls"


